import { type Registry } from "shadcn/registry";

// This file is auto-generated by scripts/build-registry.mts
// Do not edit this file manually
export const registry_lib: Registry["items"] = [
  {
    "name": "lib",
    "type": "registry:lib",
    "description": "Core library components and utilities",
    "files": [
      {
        "path": "registry/default/lib/i18n/I18nProvider.tsx",
        "type": "registry:lib",
        "target": "lib/i18n/I18nProvider.tsx"
      },
      {
        "path": "registry/default/lib/i18n/locales/en.ts",
        "type": "registry:lib",
        "target": "lib/i18n/locales/en.ts"
      },
      {
        "path": "registry/default/lib/i18n/locales/zh.ts",
        "type": "registry:lib",
        "target": "lib/i18n/locales/zh.ts"
      },
      {
        "path": "registry/default/lib/utils/generate-example.ts",
        "type": "registry:lib",
        "target": "lib/utils/generate-example.ts"
      },
      {
        "path": "registry/default/lib/utils/resolve-ref.ts",
        "type": "registry:lib",
        "target": "lib/utils/resolve-ref.ts"
      },
      {
        "path": "registry/default/lib/utils/schema-utils.ts",
        "type": "registry:lib",
        "target": "lib/utils/schema-utils.ts"
      },
      {
        "path": "registry/default/lib/utils/type-utils.ts",
        "type": "registry:lib",
        "target": "lib/utils/type-utils.ts"
      }
    ],
    "dependencies": [
      "@faker-js/faker",
      "openapi-types",
      "react"
    ]
  }
];
