import { type Registry } from "shadcn/registry";

// This file is auto-generated by scripts/build-registry.mts
// Do not edit this file manually
export const registry_hooks: Registry["items"] = [
  {
    "name": "hooks",
    "type": "registry:hook",
    "description": "React hooks collection",
    "files": [
      {
        "path": "registry/hooks/use-openapi.ts",
        "type": "registry:hook",
        "target": "hooks/use-openapi.ts"
      },
      {
        "path": "registry/hooks/use-operation.ts",
        "type": "registry:hook",
        "target": "hooks/use-operation.ts"
      },
      {
        "path": "registry/hooks/use-schema.ts",
        "type": "registry:hook",
        "target": "hooks/use-schema.ts"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ]
  }
];
