import { type Registry } from "shadcn/registry";

// This file is auto-generated by scripts/build-registry.mts
// Do not edit this file manually
export const registry_ui: Registry["items"] = [
  {
    "name": "accordion-components-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/accordion-components-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/accordion-components-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "lucide-react",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/component-detail.json"
    ]
  },
  {
    "name": "callback-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/callback-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/callback-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/operation-box.json"
    ]
  },
  {
    "name": "code-markdown",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/code-markdown.tsx",
        "type": "registry:ui",
        "target": "components/ui/code-markdown.tsx"
      }
    ],
    "dependencies": [
      "next-themes",
      "react",
      "react-syntax-highlighter"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/copy-button.json"
    ]
  },
  {
    "name": "codegen",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/codegen.tsx",
        "type": "registry:ui",
        "target": "components/ui/codegen.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "lucide-react",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/code-markdown.json"
    ]
  },
  {
    "name": "component-detail",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/component-detail.tsx",
        "type": "registry:ui",
        "target": "components/ui/component-detail.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/callback-display.json",
      "https://pivotkit.vercel.app/r/examples-display.json",
      "https://pivotkit.vercel.app/r/header-item.json",
      "https://pivotkit.vercel.app/r/link-item.json",
      "https://pivotkit.vercel.app/r/parameter-item.json",
      "https://pivotkit.vercel.app/r/request-body-section.json",
      "https://pivotkit.vercel.app/r/response-item.json",
      "https://pivotkit.vercel.app/r/schema-display.json",
      "https://pivotkit.vercel.app/r/security-scheme-display.json",
      "https://pivotkit.vercel.app/r/webhook-display.json"
    ]
  },
  {
    "name": "component-items-list",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/component-items-list.tsx",
        "type": "registry:ui",
        "target": "components/ui/component-items-list.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "component-tabs",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/component-tabs.tsx",
        "type": "registry:ui",
        "target": "components/ui/component-tabs.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "components-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/components-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/components-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/component-items-list.json",
      "https://pivotkit.vercel.app/r/component-tabs.json",
      "https://pivotkit.vercel.app/r/section-title.json"
    ]
  },
  {
    "name": "const-value",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/const-value.tsx",
        "type": "registry:ui",
        "target": "components/ui/const-value.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/copy-button.json"
    ]
  },
  {
    "name": "constraint-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/constraint-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/constraint-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ]
  },
  {
    "name": "contact-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/contact-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/contact-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ]
  },
  {
    "name": "copy-button",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/copy-button.tsx",
        "type": "registry:ui",
        "target": "components/ui/copy-button.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json"
    ]
  },
  {
    "name": "curl-generator",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/curl-generator.tsx",
        "type": "registry:ui",
        "target": "components/ui/curl-generator.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "react"
    ]
  },
  {
    "name": "default-value-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/default-value-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/default-value-display.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/value-display.json"
    ]
  },
  {
    "name": "deprecated-badge",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/deprecated-badge.tsx",
        "type": "registry:ui",
        "target": "components/ui/deprecated-badge.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "description-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/description-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/description-display.tsx"
      }
    ],
    "dependencies": [
      "react",
      "react-markdown"
    ]
  },
  {
    "name": "enum-values-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/enum-values-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/enum-values-display.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/enum-values.json"
    ]
  },
  {
    "name": "enum-values",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/enum-values.tsx",
        "type": "registry:ui",
        "target": "components/ui/enum-values.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/value-display.json"
    ]
  },
  {
    "name": "example-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/example-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/example-display.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/code-markdown.json"
    ]
  },
  {
    "name": "examples-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/examples-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/examples-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/description-display.json"
    ]
  },
  {
    "name": "expand-collapse",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/expand-collapse.tsx",
        "type": "registry:ui",
        "target": "components/ui/expand-collapse.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "external-docs-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/external-docs-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/external-docs-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ]
  },
  {
    "name": "external-docs",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/external-docs.tsx",
        "type": "registry:ui",
        "target": "components/ui/external-docs.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "format-badge",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/format-badge.tsx",
        "type": "registry:ui",
        "target": "components/ui/format-badge.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "header-item",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/header-item.tsx",
        "type": "registry:ui",
        "target": "components/ui/header-item.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/deprecated-badge.json",
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/enum-values-display.json",
      "https://pivotkit.vercel.app/r/format-badge.json",
      "https://pivotkit.vercel.app/r/required-badge.json",
      "https://pivotkit.vercel.app/r/type-indicator.json",
      "https://pivotkit.vercel.app/r/default-value-display.json",
      "https://pivotkit.vercel.app/r/examples-display.json",
      "https://pivotkit.vercel.app/r/expand-collapse.json"
    ]
  },
  {
    "name": "headers-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/headers-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/headers-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/header-item.json",
      "https://pivotkit.vercel.app/r/style-badge.json"
    ]
  },
  {
    "name": "in-label",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/in-label.tsx",
        "type": "registry:ui",
        "target": "components/ui/in-label.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "info-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/info-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/info-section.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/contact-display.json",
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/license-display.json"
    ]
  },
  {
    "name": "language-switcher",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/language-switcher.tsx",
        "type": "registry:ui",
        "target": "components/ui/language-switcher.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json"
    ]
  },
  {
    "name": "laravel-generator",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/laravel-generator.tsx",
        "type": "registry:ui",
        "target": "components/ui/laravel-generator.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "react"
    ]
  },
  {
    "name": "license-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/license-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/license-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ]
  },
  {
    "name": "link-item",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/link-item.tsx",
        "type": "registry:ui",
        "target": "components/ui/link-item.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/expand-collapse.json",
      "https://pivotkit.vercel.app/r/server-display.json"
    ]
  },
  {
    "name": "links-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/links-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/links-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/link-item.json"
    ]
  },
  {
    "name": "media-type-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/media-type-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/media-type-display.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "media-type-selector",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/media-type-selector.tsx",
        "type": "registry:ui",
        "target": "components/ui/media-type-selector.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json"
    ]
  },
  {
    "name": "method-label",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/method-label.tsx",
        "type": "registry:ui",
        "target": "components/ui/method-label.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "navigation-sidebar",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/navigation-sidebar.tsx",
        "type": "registry:ui",
        "target": "components/ui/navigation-sidebar.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "collapsible",
      "input",
      "sidebar",
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/method-label.json"
    ]
  },
  {
    "name": "oauth-flow-details",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/oauth-flow-details.tsx",
        "type": "registry:ui",
        "target": "components/ui/oauth-flow-details.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "oauth-flow",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/oauth-flow.tsx",
        "type": "registry:ui",
        "target": "components/ui/oauth-flow.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "operation-box",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/operation-box.tsx",
        "type": "registry:ui",
        "target": "components/ui/operation-box.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/deprecated-badge.json",
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/expand-collapse.json",
      "https://pivotkit.vercel.app/r/external-docs-display.json",
      "https://pivotkit.vercel.app/r/method-label.json",
      "https://pivotkit.vercel.app/r/operation-path.json",
      "https://pivotkit.vercel.app/r/parameters-section.json",
      "https://pivotkit.vercel.app/r/request-body-section.json",
      "https://pivotkit.vercel.app/r/responses-section.json",
      "https://pivotkit.vercel.app/r/security-requirements-section.json"
    ]
  },
  {
    "name": "operation-detail",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/operation-detail.tsx",
        "type": "registry:ui",
        "target": "components/ui/operation-detail.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "badge",
      "label",
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/deprecated-badge.json",
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/external-docs-display.json",
      "https://pivotkit.vercel.app/r/method-label.json",
      "https://pivotkit.vercel.app/r/operation-path.json",
      "https://pivotkit.vercel.app/r/parameters-section.json",
      "https://pivotkit.vercel.app/r/request-body-section.json",
      "https://pivotkit.vercel.app/r/responses-section.json",
      "https://pivotkit.vercel.app/r/security-requirements-section.json"
    ]
  },
  {
    "name": "operation-detailed-layout",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/operation-detailed-layout.tsx",
        "type": "registry:ui",
        "target": "components/ui/operation-detailed-layout.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "sidebar",
      "https://pivotkit.vercel.app/r/hooks.json",
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/codegen.json",
      "https://pivotkit.vercel.app/r/navigation-sidebar.json",
      "https://pivotkit.vercel.app/r/operation-detail.json",
      "https://pivotkit.vercel.app/r/try-it-out-panel.json"
    ]
  },
  {
    "name": "operation-list-layout",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/operation-list-layout.tsx",
        "type": "registry:ui",
        "target": "components/ui/operation-list-layout.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "sidebar",
      "https://pivotkit.vercel.app/r/hooks.json",
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/navigation-sidebar.json",
      "https://pivotkit.vercel.app/r/operation-box.json",
      "https://pivotkit.vercel.app/r/try-it-out-panel.json"
    ]
  },
  {
    "name": "operation-path",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/operation-path.tsx",
        "type": "registry:ui",
        "target": "components/ui/operation-path.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/path-segment.json"
    ]
  },
  {
    "name": "parameter-description",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/parameter-description.tsx",
        "type": "registry:ui",
        "target": "components/ui/parameter-description.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "parameter-group",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/parameter-group.tsx",
        "type": "registry:ui",
        "target": "components/ui/parameter-group.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/required-marker.json",
      "https://pivotkit.vercel.app/r/type-indicator.json",
      "https://pivotkit.vercel.app/r/expand-collapse.json"
    ]
  },
  {
    "name": "parameter-item",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/parameter-item.tsx",
        "type": "registry:ui",
        "target": "components/ui/parameter-item.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/constraint-display.json",
      "https://pivotkit.vercel.app/r/default-value-display.json",
      "https://pivotkit.vercel.app/r/deprecated-badge.json",
      "https://pivotkit.vercel.app/r/enum-values-display.json",
      "https://pivotkit.vercel.app/r/format-badge.json",
      "https://pivotkit.vercel.app/r/in-label.json",
      "https://pivotkit.vercel.app/r/parameter-description.json",
      "https://pivotkit.vercel.app/r/parameter-name.json",
      "https://pivotkit.vercel.app/r/style-badge.json",
      "https://pivotkit.vercel.app/r/type-indicator.json",
      "https://pivotkit.vercel.app/r/example-display.json",
      "https://pivotkit.vercel.app/r/expand-collapse.json"
    ]
  },
  {
    "name": "parameter-name",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/parameter-name.tsx",
        "type": "registry:ui",
        "target": "components/ui/parameter-name.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "parameters-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/parameters-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/parameters-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/parameter-item.json",
      "https://pivotkit.vercel.app/r/section-title.json",
      "https://pivotkit.vercel.app/r/style-badge.json"
    ]
  },
  {
    "name": "path-item-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/path-item-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/path-item-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/operation-box.json"
    ]
  },
  {
    "name": "path-segment",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/path-segment.tsx",
        "type": "registry:ui",
        "target": "components/ui/path-segment.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "php-generator",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/php-generator.tsx",
        "type": "registry:ui",
        "target": "components/ui/php-generator.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "react"
    ]
  },
  {
    "name": "python-generator",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/python-generator.tsx",
        "type": "registry:ui",
        "target": "components/ui/python-generator.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "react"
    ]
  },
  {
    "name": "request-body-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/request-body-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/request-body-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/schema-with-example-viewer.json",
      "https://pivotkit.vercel.app/r/section-title.json"
    ]
  },
  {
    "name": "required-badge",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/required-badge.tsx",
        "type": "registry:ui",
        "target": "components/ui/required-badge.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "required-marker",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/required-marker.tsx",
        "type": "registry:ui",
        "target": "components/ui/required-marker.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "resizable-sidebar",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/resizable-sidebar.tsx",
        "type": "registry:ui",
        "target": "components/ui/resizable-sidebar.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "response-content-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/response-content-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/response-content-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/schema-with-example-viewer.json"
    ]
  },
  {
    "name": "response-group",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/response-group.tsx",
        "type": "registry:ui",
        "target": "components/ui/response-group.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/response-content-section.json",
      "https://pivotkit.vercel.app/r/response-headers-table.json"
    ]
  },
  {
    "name": "response-headers-table",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/response-headers-table.tsx",
        "type": "registry:ui",
        "target": "components/ui/response-headers-table.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/header-item.json",
      "https://pivotkit.vercel.app/r/style-badge.json"
    ]
  },
  {
    "name": "response-item",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/response-item.tsx",
        "type": "registry:ui",
        "target": "components/ui/response-item.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/headers-section.json",
      "https://pivotkit.vercel.app/r/links-section.json",
      "https://pivotkit.vercel.app/r/status-code.json"
    ]
  },
  {
    "name": "responses-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/responses-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/responses-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/response-group.json",
      "https://pivotkit.vercel.app/r/section-title.json",
      "https://pivotkit.vercel.app/r/status-code.json"
    ]
  },
  {
    "name": "schema-composition-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/schema-composition-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/schema-composition-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ]
  },
  {
    "name": "schema-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/schema-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/schema-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/constraint-display.json",
      "https://pivotkit.vercel.app/r/default-value-display.json",
      "https://pivotkit.vercel.app/r/deprecated-badge.json",
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/enum-values-display.json",
      "https://pivotkit.vercel.app/r/format-badge.json",
      "https://pivotkit.vercel.app/r/required-badge.json",
      "https://pivotkit.vercel.app/r/schema-composition-display.json",
      "https://pivotkit.vercel.app/r/type-indicator.json"
    ]
  },
  {
    "name": "schema-with-example-viewer",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/schema-with-example-viewer.tsx",
        "type": "registry:ui",
        "target": "components/ui/schema-with-example-viewer.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/example-display.json",
      "https://pivotkit.vercel.app/r/media-type-selector.json",
      "https://pivotkit.vercel.app/r/schema-display.json"
    ]
  },
  {
    "name": "scheme-type",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/scheme-type.tsx",
        "type": "registry:ui",
        "target": "components/ui/scheme-type.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "section-title",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/section-title.tsx",
        "type": "registry:ui",
        "target": "components/ui/section-title.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "security-requirement-item",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/security-requirement-item.tsx",
        "type": "registry:ui",
        "target": "components/ui/security-requirement-item.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ]
  },
  {
    "name": "security-requirements-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/security-requirements-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/security-requirements-section.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/section-title.json",
      "https://pivotkit.vercel.app/r/security-requirement-item.json"
    ]
  },
  {
    "name": "security-scheme-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/security-scheme-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/security-scheme-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/description-display.json"
    ]
  },
  {
    "name": "security-scheme",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/security-scheme.tsx",
        "type": "registry:ui",
        "target": "components/ui/security-scheme.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/scheme-type.json"
    ]
  },
  {
    "name": "security-schemes",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/security-schemes.tsx",
        "type": "registry:ui",
        "target": "components/ui/security-schemes.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/section-title.json",
      "https://pivotkit.vercel.app/r/security-scheme.json"
    ]
  },
  {
    "name": "security-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/security-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/security-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/section-title.json",
      "https://pivotkit.vercel.app/r/security-scheme-display.json"
    ]
  },
  {
    "name": "server-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/server-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/server-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/description-display.json"
    ]
  },
  {
    "name": "server-variable",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/server-variable.tsx",
        "type": "registry:ui",
        "target": "components/ui/server-variable.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/description-display.json"
    ]
  },
  {
    "name": "server",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/server.tsx",
        "type": "registry:ui",
        "target": "components/ui/server.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/expand-collapse.json",
      "https://pivotkit.vercel.app/r/server-variable.json"
    ]
  },
  {
    "name": "servers-section",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/servers-section.tsx",
        "type": "registry:ui",
        "target": "components/ui/servers-section.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/section-title.json",
      "https://pivotkit.vercel.app/r/server-display.json"
    ]
  },
  {
    "name": "servers",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/servers.tsx",
        "type": "registry:ui",
        "target": "components/ui/servers.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/section-title.json",
      "https://pivotkit.vercel.app/r/server.json"
    ]
  },
  {
    "name": "status-code",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/status-code.tsx",
        "type": "registry:ui",
        "target": "components/ui/status-code.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "style-badge",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/style-badge.tsx",
        "type": "registry:ui",
        "target": "components/ui/style-badge.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "terms-of-service",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/terms-of-service.tsx",
        "type": "registry:ui",
        "target": "components/ui/terms-of-service.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "theme-toggle",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/theme-toggle.tsx",
        "type": "registry:ui",
        "target": "components/ui/theme-toggle.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "react"
    ]
  },
  {
    "name": "try-it-out-panel",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/try-it-out-panel.tsx",
        "type": "registry:ui",
        "target": "components/ui/try-it-out-panel.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/method-label.json"
    ]
  },
  {
    "name": "type-indicator",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/type-indicator.tsx",
        "type": "registry:ui",
        "target": "components/ui/type-indicator.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json"
    ]
  },
  {
    "name": "typescript-generator",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/typescript-generator.tsx",
        "type": "registry:ui",
        "target": "components/ui/typescript-generator.tsx"
      }
    ],
    "dependencies": [
      "lucide-react",
      "react"
    ]
  },
  {
    "name": "value-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/value-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/value-display.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "version-badge",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/version-badge.tsx",
        "type": "registry:ui",
        "target": "components/ui/version-badge.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  },
  {
    "name": "webhook-display",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/webhook-display.tsx",
        "type": "registry:ui",
        "target": "components/ui/webhook-display.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/description-display.json",
      "https://pivotkit.vercel.app/r/webhook-label.json",
      "https://pivotkit.vercel.app/r/operation-box.json"
    ]
  },
  {
    "name": "webhook-label",
    "type": "registry:ui",
    "files": [
      {
        "path": "registry/default/ui/webhook-label.tsx",
        "type": "registry:ui",
        "target": "components/ui/webhook-label.tsx"
      }
    ],
    "dependencies": [
      "react"
    ]
  }
];
