import { type Registry } from "shadcn/registry";

// This file is auto-generated by scripts/build-registry.mts
// Do not edit this file manually
export const lib: Registry["items"] = [{
  "name": "lib",
  "type": "registry:lib",
  "description": "Core library components and utilities",
  "files": [
    {
      "path": "registry/lib/hooks/use-openapi.ts",
      "type": "registry:lib",
      "target": "lib/hooks/use-openapi.ts"
    },
    {
      "path": "registry/lib/hooks/use-operation.ts",
      "type": "registry:lib",
      "target": "lib/hooks/use-operation.ts"
    },
    {
      "path": "registry/lib/hooks/use-schema.ts",
      "type": "registry:lib",
      "target": "lib/hooks/use-schema.ts"
    },
    {
      "path": "registry/lib/i18n/I18nProvider.tsx",
      "type": "registry:lib",
      "target": "lib/i18n/I18nProvider.tsx"
    },
    {
      "path": "registry/lib/utils/generate-example.ts",
      "type": "registry:lib",
      "target": "lib/utils/generate-example.ts"
    },
    {
      "path": "registry/lib/utils/resolve-ref.ts",
      "type": "registry:lib",
      "target": "lib/utils/resolve-ref.ts"
    },
    {
      "path": "registry/lib/utils/schema-utils.ts",
      "type": "registry:lib",
      "target": "lib/utils/schema-utils.ts"
    },
    {
      "path": "registry/lib/utils/type-utils.ts",
      "type": "registry:lib",
      "target": "lib/utils/type-utils.ts"
    }
  ],
  "dependencies": [
    "@faker-js/faker",
    "openapi-types",
    "react"
  ],
  "registryDependencies": [
    "https://pivotkit.vercel.app/r/en",
    "https://pivotkit.vercel.app/r/lib",
    "https://pivotkit.vercel.app/r/resolve-ref",
    "https://pivotkit.vercel.app/r/zh"
  ]
}];
