import { type Registry } from "shadcn/registry";

// This file is auto-generated by scripts/build-registry.mts
// Do not edit this file manually
export const registry_examples: Registry["items"] = [
  {
    "name": "accordion-components-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/accordion-components-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/accordion-components-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/accordion-components-section.json"
    ]
  },
  {
    "name": "callback-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/callback-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/callback-display-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/callback-display.json"
    ]
  },
  {
    "name": "code-markdown-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/code-markdown-demo.tsx",
        "type": "registry:example",
        "target": "components/example/code-markdown-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/code-markdown.json"
    ]
  },
  {
    "name": "codegen-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/codegen-demo.tsx",
        "type": "registry:example",
        "target": "components/example/codegen-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/codegen.json"
    ]
  },
  {
    "name": "component-detail-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/component-detail-demo.tsx",
        "type": "registry:example",
        "target": "components/example/component-detail-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/component-detail.json"
    ]
  },
  {
    "name": "component-items-list-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/component-items-list-demo.tsx",
        "type": "registry:example",
        "target": "components/example/component-items-list-demo.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/component-items-list.json"
    ]
  },
  {
    "name": "component-tabs-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/component-tabs-demo.tsx",
        "type": "registry:example",
        "target": "components/example/component-tabs-demo.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/component-tabs.json"
    ]
  },
  {
    "name": "components-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/components-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/components-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/components-section.json"
    ]
  },
  {
    "name": "const-value-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/const-value-demo.tsx",
        "type": "registry:example",
        "target": "components/example/const-value-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/const-value.json"
    ]
  },
  {
    "name": "constraint-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/constraint-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/constraint-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/constraint-display.json"
    ]
  },
  {
    "name": "contact-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/contact-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/contact-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/contact-display.json"
    ]
  },
  {
    "name": "copy-button-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/copy-button-demo.tsx",
        "type": "registry:example",
        "target": "components/example/copy-button-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/copy-button.json",
      "https://pivotkit.vercel.app/r/example-display.json"
    ]
  },
  {
    "name": "curl-generator-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/curl-generator-demo.tsx",
        "type": "registry:example",
        "target": "components/example/curl-generator-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/curl-generator.json"
    ]
  },
  {
    "name": "default-value-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/default-value-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/default-value-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/default-value-display.json"
    ]
  },
  {
    "name": "deprecated-badge-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/deprecated-badge-demo.tsx",
        "type": "registry:example",
        "target": "components/example/deprecated-badge-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/deprecated-badge.json"
    ]
  },
  {
    "name": "description-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/description-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/description-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/description-display.json"
    ]
  },
  {
    "name": "enum-values-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/enum-values-demo.tsx",
        "type": "registry:example",
        "target": "components/example/enum-values-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/enum-values.json"
    ]
  },
  {
    "name": "enum-values-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/enum-values-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/enum-values-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/enum-values-display.json"
    ]
  },
  {
    "name": "example-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/example-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/example-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/example-display.json"
    ]
  },
  {
    "name": "examples-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/examples-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/examples-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/examples-display.json"
    ]
  },
  {
    "name": "expand-collapse-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/expand-collapse-demo.tsx",
        "type": "registry:example",
        "target": "components/example/expand-collapse-demo.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/expand-collapse.json"
    ]
  },
  {
    "name": "external-docs-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/external-docs-demo.tsx",
        "type": "registry:example",
        "target": "components/example/external-docs-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/external-docs.json"
    ]
  },
  {
    "name": "external-docs-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/external-docs-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/external-docs-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/external-docs-display.json"
    ]
  },
  {
    "name": "faker-example-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/faker-example-demo.tsx",
        "type": "registry:example",
        "target": "components/example/faker-example-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json"
    ]
  },
  {
    "name": "format-badge-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/format-badge-demo.tsx",
        "type": "registry:example",
        "target": "components/example/format-badge-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/format-badge.json"
    ]
  },
  {
    "name": "header-item-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/header-item-demo.tsx",
        "type": "registry:example",
        "target": "components/example/header-item-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/header-item.json"
    ]
  },
  {
    "name": "headers-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/headers-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/headers-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/headers-section.json"
    ]
  },
  {
    "name": "i18n-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/i18n-demo.tsx",
        "type": "registry:example",
        "target": "components/example/i18n-demo.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "button",
      "card",
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/required-marker.json",
      "https://pivotkit.vercel.app/r/try-it-out-panel.json"
    ]
  },
  {
    "name": "in-label-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/in-label-demo.tsx",
        "type": "registry:example",
        "target": "components/example/in-label-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/in-label.json"
    ]
  },
  {
    "name": "info-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/info-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/info-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/info-section.json"
    ]
  },
  {
    "name": "language-switcher-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/language-switcher-demo.tsx",
        "type": "registry:example",
        "target": "components/example/language-switcher-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/language-switcher.json"
    ]
  },
  {
    "name": "laravel-generator-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/laravel-generator-demo.tsx",
        "type": "registry:example",
        "target": "components/example/laravel-generator-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/laravel-generator.json"
    ]
  },
  {
    "name": "license-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/license-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/license-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/license-display.json"
    ]
  },
  {
    "name": "link-item-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/link-item-demo.tsx",
        "type": "registry:example",
        "target": "components/example/link-item-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/link-item.json"
    ]
  },
  {
    "name": "links-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/links-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/links-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/links-section.json"
    ]
  },
  {
    "name": "media-type-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/media-type-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/media-type-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/media-type-display.json"
    ]
  },
  {
    "name": "media-type-selector-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/media-type-selector-demo.tsx",
        "type": "registry:example",
        "target": "components/example/media-type-selector-demo.tsx"
      }
    ],
    "dependencies": [
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/media-type-selector.json"
    ]
  },
  {
    "name": "method-label-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/method-label-demo.tsx",
        "type": "registry:example",
        "target": "components/example/method-label-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/method-label.json"
    ]
  },
  {
    "name": "navigation-sidebar-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/navigation-sidebar-demo.tsx",
        "type": "registry:example",
        "target": "components/example/navigation-sidebar-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "sidebar",
      "https://pivotkit.vercel.app/r/navigation-sidebar.json"
    ]
  },
  {
    "name": "oauth-flow-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/oauth-flow-demo.tsx",
        "type": "registry:example",
        "target": "components/example/oauth-flow-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/oauth-flow.json"
    ]
  },
  {
    "name": "oauth-flow-details-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/oauth-flow-details-demo.tsx",
        "type": "registry:example",
        "target": "components/example/oauth-flow-details-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/oauth-flow-details.json"
    ]
  },
  {
    "name": "openapi-viewer-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/openapi-viewer-demo.tsx",
        "type": "registry:example",
        "target": "components/example/openapi-viewer-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/openapi-viewer.json"
    ]
  },
  {
    "name": "operation-box-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/operation-box-demo.tsx",
        "type": "registry:example",
        "target": "components/example/operation-box-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/operation-box.json"
    ]
  },
  {
    "name": "operation-detail-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/operation-detail-demo.tsx",
        "type": "registry:example",
        "target": "components/example/operation-detail-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/operation-detail.json"
    ]
  },
  {
    "name": "operation-detailed-layout-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/operation-detailed-layout-demo.tsx",
        "type": "registry:example",
        "target": "components/example/operation-detailed-layout-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/operation-detailed-layout.json"
    ]
  },
  {
    "name": "operation-list-layout-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/operation-list-layout-demo.tsx",
        "type": "registry:example",
        "target": "components/example/operation-list-layout-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types",
      "react"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/operation-list-layout.json"
    ]
  },
  {
    "name": "operation-path-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/operation-path-demo.tsx",
        "type": "registry:example",
        "target": "components/example/operation-path-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/operation-path.json"
    ]
  },
  {
    "name": "parameter-description-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/parameter-description-demo.tsx",
        "type": "registry:example",
        "target": "components/example/parameter-description-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/parameter-description.json"
    ]
  },
  {
    "name": "parameter-group-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/parameter-group-demo.tsx",
        "type": "registry:example",
        "target": "components/example/parameter-group-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/parameter-group.json"
    ]
  },
  {
    "name": "parameter-item-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/parameter-item-demo.tsx",
        "type": "registry:example",
        "target": "components/example/parameter-item-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/parameter-item.json"
    ]
  },
  {
    "name": "parameter-name-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/parameter-name-demo.tsx",
        "type": "registry:example",
        "target": "components/example/parameter-name-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/parameter-name.json"
    ]
  },
  {
    "name": "parameters-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/parameters-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/parameters-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/parameters-section.json"
    ]
  },
  {
    "name": "path-segment-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/path-segment-demo.tsx",
        "type": "registry:example",
        "target": "components/example/path-segment-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/path-segment.json"
    ]
  },
  {
    "name": "php-generator-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/php-generator-demo.tsx",
        "type": "registry:example",
        "target": "components/example/php-generator-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/php-generator.json"
    ]
  },
  {
    "name": "python-generator-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/python-generator-demo.tsx",
        "type": "registry:example",
        "target": "components/example/python-generator-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/python-generator.json"
    ]
  },
  {
    "name": "request-body-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/request-body-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/request-body-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/request-body-section.json"
    ]
  },
  {
    "name": "required-badge-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/required-badge-demo.tsx",
        "type": "registry:example",
        "target": "components/example/required-badge-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/required-badge.json"
    ]
  },
  {
    "name": "required-marker-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/required-marker-demo.tsx",
        "type": "registry:example",
        "target": "components/example/required-marker-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/required-marker.json"
    ]
  },
  {
    "name": "resizable-sidebar-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/resizable-sidebar-demo.tsx",
        "type": "registry:example",
        "target": "components/example/resizable-sidebar-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/resizable-sidebar.json"
    ]
  },
  {
    "name": "response-content-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/response-content-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/response-content-section-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/lib.json",
      "https://pivotkit.vercel.app/r/response-content-section.json"
    ]
  },
  {
    "name": "response-headers-table-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/response-headers-table-demo.tsx",
        "type": "registry:example",
        "target": "components/example/response-headers-table-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/response-headers-table.json"
    ]
  },
  {
    "name": "response-item-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/response-item-demo.tsx",
        "type": "registry:example",
        "target": "components/example/response-item-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/response-item.json"
    ]
  },
  {
    "name": "responses-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/responses-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/responses-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/responses-section.json"
    ]
  },
  {
    "name": "schema-composition-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/schema-composition-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/schema-composition-display-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/schema-composition-display.json"
    ]
  },
  {
    "name": "schema-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/schema-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/schema-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/schema-display.json"
    ]
  },
  {
    "name": "schema-with-example-viewer-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/schema-with-example-viewer-demo.tsx",
        "type": "registry:example",
        "target": "components/example/schema-with-example-viewer-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/schema-with-example-viewer.json"
    ]
  },
  {
    "name": "scheme-type-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/scheme-type-demo.tsx",
        "type": "registry:example",
        "target": "components/example/scheme-type-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/scheme-type.json"
    ]
  },
  {
    "name": "section-title-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/section-title-demo.tsx",
        "type": "registry:example",
        "target": "components/example/section-title-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/section-title.json"
    ]
  },
  {
    "name": "security-requirement-item-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/security-requirement-item-demo.tsx",
        "type": "registry:example",
        "target": "components/example/security-requirement-item-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/security-requirement-item.json"
    ]
  },
  {
    "name": "security-requirements-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/security-requirements-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/security-requirements-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/security-requirements-section.json"
    ]
  },
  {
    "name": "security-scheme-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/security-scheme-demo.tsx",
        "type": "registry:example",
        "target": "components/example/security-scheme-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/security-scheme.json"
    ]
  },
  {
    "name": "security-scheme-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/security-scheme-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/security-scheme-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/security-scheme-display.json"
    ]
  },
  {
    "name": "security-schemes-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/security-schemes-demo.tsx",
        "type": "registry:example",
        "target": "components/example/security-schemes-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/security-schemes.json"
    ]
  },
  {
    "name": "security-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/security-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/security-section-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/security-section.json"
    ]
  },
  {
    "name": "server-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/server-demo.tsx",
        "type": "registry:example",
        "target": "components/example/server-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/server.json"
    ]
  },
  {
    "name": "server-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/server-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/server-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/server-display.json"
    ]
  },
  {
    "name": "server-variable-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/server-variable-demo.tsx",
        "type": "registry:example",
        "target": "components/example/server-variable-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/server-variable.json"
    ]
  },
  {
    "name": "servers-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/servers-demo.tsx",
        "type": "registry:example",
        "target": "components/example/servers-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/server.json",
      "https://pivotkit.vercel.app/r/servers.json"
    ]
  },
  {
    "name": "servers-section-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/servers-section-demo.tsx",
        "type": "registry:example",
        "target": "components/example/servers-section-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/server.json",
      "https://pivotkit.vercel.app/r/servers-section.json"
    ]
  },
  {
    "name": "status-code-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/status-code-demo.tsx",
        "type": "registry:example",
        "target": "components/example/status-code-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/status-code.json"
    ]
  },
  {
    "name": "style-badge-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/style-badge-demo.tsx",
        "type": "registry:example",
        "target": "components/example/style-badge-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/style-badge.json"
    ]
  },
  {
    "name": "terms-of-service-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/terms-of-service-demo.tsx",
        "type": "registry:example",
        "target": "components/example/terms-of-service-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/terms-of-service.json"
    ]
  },
  {
    "name": "theme-toggle-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/theme-toggle-demo.tsx",
        "type": "registry:example",
        "target": "components/example/theme-toggle-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/theme-toggle.json"
    ]
  },
  {
    "name": "try-it-out-panel-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/try-it-out-panel-demo.tsx",
        "type": "registry:example",
        "target": "components/example/try-it-out-panel-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/try-it-out-panel.json"
    ]
  },
  {
    "name": "type-indicator-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/type-indicator-demo.tsx",
        "type": "registry:example",
        "target": "components/example/type-indicator-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/type-indicator.json"
    ]
  },
  {
    "name": "typescript-generator-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/typescript-generator-demo.tsx",
        "type": "registry:example",
        "target": "components/example/typescript-generator-demo.tsx"
      }
    ],
    "dependencies": [
      "openapi-types"
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/typescript-generator.json"
    ]
  },
  {
    "name": "value-display-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/value-display-demo.tsx",
        "type": "registry:example",
        "target": "components/example/value-display-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/value-display.json"
    ]
  },
  {
    "name": "version-badge-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/version-badge-demo.tsx",
        "type": "registry:example",
        "target": "components/example/version-badge-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/version-badge.json"
    ]
  },
  {
    "name": "webhook-label-demo",
    "type": "registry:example",
    "files": [
      {
        "path": "registry/default/example/webhook-label-demo.tsx",
        "type": "registry:example",
        "target": "components/example/webhook-label-demo.tsx"
      }
    ],
    "registryDependencies": [
      "https://pivotkit.vercel.app/r/webhook-label.json"
    ]
  }
];
